<?php

/**
 * @file
 * islandora_genetic_edition.install
 */

/**
 * Implements hook_install().
 *
 * @see islandora_genetic_edition_islandora_required_objects()
 */
function islandora_genetic_edition_install() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  islandora_install_solution_pack('islandora_genetic_edition');
}

/**
 * Implements hook_uninstall().
 */
function islandora_genetic_edition_uninstall() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  islandora_install_solution_pack('islandora_genetic_edition', 'uninstall');
  $variables = array('islandora_genetic_edition_collatex_server_url', 'islandora_genetic_edition_page_viewers');
  array_walk($variables, 'variable_del');
}
