<?php

/**
 * @file
 * Install hooks for this module.
 */

/**
 * Implements hook_install().
 *
 * @see islandora_book_islandora_required_objects()
 */
function islandora_genetic_edition_install() {
}

/**
 * Implements hook_uninstall().
 */
function islandora_genetic_edition_uninstall() {
  $variables = array(
    #'islandora_scholar_use_standard_metadata_display',
  );
  array_walk($variables, 'variable_del');
}
