<?php

/**
 * @file
 * The islandora_genetic_edition module.
 */

/**
 * Implements hook_menu().
 */
function islandora_genetic_edition_menu() {
  $menu = array();

  // Admin menu
  $menu['admin/islandora/solution_pack_config/genetic_edition'] = array(
    'title' => 'Genetic Editions',
    'description' => 'Configure Collatex server connection and select page viewer.',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('islandora_genetic_edition_admin_settings_form'),
    'file' => 'includes/admin.form.inc',
    'type' => MENU_NORMAL_ITEM,
  );


  $menu['islandora/object/%islandora_object/manage/attach_witness'] = array(
    'title' => 'Attach Witness',
    'access callback' => 'islandora_genetic_edition_attach_witness_access',
    'access arguments' => array(2),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_genetic_edition_attach_witness_form', 2),
    'file' => 'includes/attach_witness.form.inc',
    'type' => MENU_LOCAL_ACTION,
    'weight' => 1,
  );

  return $menu;
}

/**
 * Menu access callback.
 */
function islandora_genetic_edition_attach_witness_access($object) {
  if (!islandora_object_access(ISLANDORA_INGEST, $object)) {
    return FALSE;
  }
  return in_array('islandora:geneticEditionCModel', $object->models);
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_genetic_edition_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_genetic_edition');

  // Genetic Edition content model.
  $genetic_edition_content_model = $connection->repository->constructObject('islandora:geneticEditionCModel');
  $genetic_edition_content_model->owner = 'fedoraAdmin';
  $genetic_edition_content_model->label = 'Islandora Genetic Edition Content Model';
  $genetic_edition_content_model->models = 'fedora-system:ContentModel-3.0';
  
  // DS-COMPOSITE-MODEL datastream.
  $ge_model_ds = $genetic_edition_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $ge_model_ds->label = 'DS-COMPOSITE-MODEL';
  $ge_model_ds->mimetype = 'application/xml';
  $ge_model_ds->setContentFromFile("$module_path/xml/content_models/islandora_genetic_edition_ds_composite_model.xml", FALSE);
  $genetic_edition_content_model->ingestDatastream($ge_model_ds);

  // Witness content model.
  $genetic_edition_witness_content_model = $connection->repository->constructObject('islandora:geneticEditionWitnessCModel');
  $genetic_edition_witness_content_model->owner = 'fedoraAdmin';
  $genetic_edition_witness_content_model->label = 'Islandora Genetic Edition Witness Content Model';
  $genetic_edition_witness_content_model->models = 'fedora-system:ContentModel-3.0';
  
  // DS-COMPOSITE-MODEL datastream.
  $witness_model_ds = $genetic_edition_witness_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $witness_model_ds->label = 'DS-COMPOSITE-MODEL';
  $witness_model_ds->mimetype = 'application/xml';
  $witness_model_ds->setContentFromFile("$module_path/xml/content_models/islandora_genetic_edition_witness_ds_composite_model.xml", FALSE);
  $genetic_edition_witness_content_model->ingestDatastream($witness_model_ds);

  // Page content model.
  $genetic_edition_page_content_model = $connection->repository->constructObject('islandora:geneticEditionPageCModel');
  $genetic_edition_page_content_model->owner = 'fedoraAdmin';
  $genetic_edition_page_content_model->label = 'Islandora Genetic Edition Page Content Model';
  $genetic_edition_page_content_model->models = 'fedora-system:ContentModel-3.0';
  
  // DS-COMPOSITE-MODEL datastream.
  $page_model_ds = $genetic_edition_page_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $page_model_ds->label = 'DS-COMPOSITE-MODEL';
  $page_model_ds->mimetype = 'application/xml';
  $page_model_ds->setContentFromFile("$module_path/xml/content_models/islandora_genetic_edition_page_ds_composite_model.xml", FALSE);
  $genetic_edition_page_content_model->ingestDatastream($page_model_ds);

  // Genetic Edition collection.
  $genetic_edition_collection = $connection->repository->constructObject('islandora:genetic_edition_collection');
  $genetic_edition_collection->owner = 'fedoraAdmin';
  $genetic_edition_collection->label = 'Genetic Edition Collection';
  $genetic_edition_collection->models = 'islandora:collectionCModel';
  $genetic_edition_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  
  // Collection policy datastream.
  $ge_collection_policy_ds = $genetic_edition_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $ge_collection_policy_ds->label = 'Collection policy';
  $ge_collection_policy_ds->mimetype = 'application/xml';
  $ge_collection_policy_ds->setContentFromFile("$module_path/xml/collection/islandora_genetic_edition_collection_policy.xml", FALSE);
  $genetic_edition_collection->ingestDatastream($ge_collection_policy_ds);
  
  // TN datastream.
  $ge_collection_tn_ds = $genetic_edition_collection->constructDatastream('TN', 'M');
  $ge_collection_tn_ds->label = 'Thumbnail';
  $ge_collection_tn_ds->mimetype = 'image/png';
  $ge_collection_tn_ds->setContentFromFile("$module_path/images/folder.png", FALSE);
  $genetic_edition_collection->ingestDatastream($ge_collection_tn_ds);

  return array(
    'islandora_genetic_edition' => array(
      'title' => 'Islandora Genetic Edition',
      'objects' => array(
        $genetic_edition_content_model,
        $genetic_edition_witness_content_model,
        $genetic_edition_page_content_model,
        $genetic_edition_collection,
      ),
    ),
  );
}

/**
 * Implements hook_islandora_view_object().
 */
function islandora_genetic_edition_islandora_geneticEditionCModel_islandora_view_object($object) {
  $output = theme('islandora_genetic_edition', array('islandora_object' => $object));
  return array('' => $output);
}

function islandora_genetic_edition_islandora_geneticEditionWitnessCModel_islandora_view_object($object) {
  $output = theme('islandora_genetic_edition_witness', array('islandora_object' => $object));
  return array('' => $output);
}

function islandora_genetic_edition_islandora_geneticEditionPageCModel_islandora_view_object($object) {
  $output = theme('islandora_genetic_edition_page', array('islandora_object' => $object));
  return array('' => $output);
}

/**
 * Implements hook_theme().
 */
function islandora_genetic_edition_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_genetic_edition' => array(
      'path' => drupal_get_path('module', 'islandora_genetic_edition').'/theme',
      'template' => 'islandora-genetic-edition',
      'variables' => array('islandora_object' => NULL, 'display' => NULL),
    ),
    'islandora_genetic_edition_witness' => array(
      'path' => drupal_get_path('module', 'islandora_genetic_edition').'/theme',
      'template' => 'islandora-genetic-edition-witness',
      'variables' => array('islandora_object' => NULL, 'display' => NULL),
    ),
    'islandora_genetic_edition_page' => array(
      'path' => drupal_get_path('module', 'islandora_genetic_edition').'/theme',
      'template' => 'islandora-genetic-edition-page',
      'variables' => array('islandora_object' => NULL, 'display' => NULL),
    ),
  );  
}

/**
 * Implements template_preprocess_HOOK().
 */
function template_preprocess_islandora_genetic_edition(&$variables) {
  drupal_add_library ( 'system' , 'ui.tabs' );
  drupal_add_css(drupal_get_path('module', 'islandora_genetic_edition') . '/css/islandora_genetic_edition.css');
  drupal_add_js(drupal_get_path('module', 'islandora_genetic_edition') . '/js/islandora_genetic_edition.js');
  
  $mods_string = $variables['islandora_object']['MODS']->content;
  $variables['mods_obj'] = simplexml_load_string($mods_string);
}

/**
 * Implements template_preprocess_HOOK().
 */
function template_preprocess_islandora_genetic_edition_witness(&$variables) {
  drupal_add_css(drupal_get_path('module', 'islandora_genetic_edition') . '/css/islandora_genetic_edition.css');
  drupal_add_js(drupal_get_path('module', 'islandora_genetic_edition') . '/js/islandora_genetic_edition.js');
}

/**
 * Implements template_preprocess_HOOK().
 */
function template_preprocess_islandora_genetic_edition_page(&$variables) {
  drupal_add_library( 'system' , 'ui.tabs' );
  drupal_add_css(drupal_get_path('module', 'islandora_genetic_edition') . '/css/islandora_genetic_edition.css');
  drupal_add_js(drupal_get_path('module', 'islandora_genetic_edition') . '/js/islandora_genetic_edition.js');
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  
  $islandora_object = $variables['islandora_object'];
  
  if(isset($islandora_object['JP2'])) {
    $params = array();
    $jp2_url = url("islandora/object/{$islandora_object->id}/datastream/JP2/view",
      array(
      'absolute' => TRUE,
      ));
    $params['jp2_url'] = $jp2_url; 
    $viewer = islandora_get_viewer($params, 'islandora_genetic_edition_page_viewers', $islandora_object);
  }
  
  if ($viewer) {
    $variables['page_image'] = $viewer;
  } else {
    $variables['page_image'] = "<img src='/islandora/object/{$islandora_object->id}/datastream/OBJ/view'>";
  }
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_genetic_edition_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_genetic_edition');
  return array(
    'Genetic Edition' => array(
      'form_file' => "$module_path/xml/forms/islandora_genetic_edition_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_form_associations().
 */
function islandora_genetic_edition_islandora_xml_form_builder_form_associations() {
  return array(
    'islandora_genetic_edition_mods_form' => array(
      'content_model' => 'islandora:geneticEditionCModel',
      'form_name' => 'Genetic Edition',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_genetic_edition_islandora_geneticEditionCModel_islandora_ingest_steps() {
  return array(
    'islandora_gened_file_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_genetic_edition_gened_upload_form',
      'module' => 'islandora_genetic_edition',
      'file' => 'includes/gened_upload.form.inc',
    ),
  );
}

/**
 * Implements hook_CMODEL_islandora_derivative().
 */
function islandora_genetic_edition_islandora_geneticEditionCModel_islandora_derivative() {
  $mod_path = drupal_get_path('module', 'islandora_genetic_edition');
  return array(
    array(
      'source_dsid' => 'OBJ',
      'destination_dsid' => 'TN',
      'weight' => 0,
      'function' => array(
        'islandora_genetic_edition_create_tn_derivative',
      ),
      'file' => "$mod_path/includes/derivatives.inc",
    ),
  );
}

/**
 * Implements hook_islandora_breadcrumbs_alter().
 */
function islandora_genetic_edition_islandora_breadcrumbs_alter(&$breadcrumbs, $context, $object = NULL) {
  module_load_include('inc', 'islandora_genetic_edition', 'includes/breadcrumb');
  if (in_array('islandora:geneticEditionWitnessCModel', $object->models)) {
    $gened_parent = _get_genetic_parent($object);
    $gened_parent_collection = _get_collection_parent($gened_parent);
    $breadcrumbs[] = _create_breadcrumb_html($gened_parent_collection);
    $breadcrumbs[] = _create_breadcrumb_html($gened_parent);
  }
  if (in_array('islandora:geneticEditionPageCModel', $object->models)) {
    $witness_parent = _get_genetic_parent($object);
    $gened_parent = _get_genetic_parent($witness_parent);
    $gened_parent_collection = _get_collection_parent($gened_parent);
    $breadcrumbs[] = _create_breadcrumb_html($gened_parent_collection);
    $breadcrumbs[] = _create_breadcrumb_html($gened_parent);
    $breadcrumbs[] = _create_breadcrumb_html($witness_parent);
  }
}
