<?php

/**
 * @file
 * The islandora_genetic_edition module.
 */

/**
 * Implements hook_menu().
 */
function islandora_genetic_edition_menu() {
  $menu = array();
  $menu['admin/islandora/solution_pack_config/genetic_edition'] = array(
    'title' => 'Genetic Editions',
    'description' => 'Configure Collatex server connection and select page viewer.',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('islandora_genetic_edition_admin_settings_form'),
    'file' => 'includes/admin.form.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $menu;
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_genetic_edition_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_genetic_edition');

  // Genetic Edition content model.
  $genetic_edition_content_model = $connection->repository->constructObject('islandora:geneticEditionCModel');
  $genetic_edition_content_model->owner = 'fedoraAdmin';
  $genetic_edition_content_model->label = 'Islandora Genetic Edition Content Model';
  $genetic_edition_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL datastream.
  $ge_model_ds = $genetic_edition_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $ge_model_ds->label = 'DS-COMPOSITE-MODEL';
  $ge_model_ds->mimetype = 'application/xml';
  $ge_model_ds->setContentFromFile("$module_path/xml/content_models/islandora_genetic_edition_ds_composite_model.xml", FALSE);
  $genetic_edition_content_model->ingestDatastream($ge_model_ds);

  // Witness content model.
  $genetic_edition_witness_content_model = $connection->repository->constructObject('islandora:geneticEditionWitnessCModel');
  $genetic_edition_witness_content_model->owner = 'fedoraAdmin';
  $genetic_edition_witness_content_model->label = 'Islandora Genetic Edition Witness Content Model';
  $genetic_edition_witness_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL datastream.
  $witness_model_ds = $genetic_edition_witness_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $witness_model_ds->label = 'DS-COMPOSITE-MODEL';
  $witness_model_ds->mimetype = 'application/xml';
  $witness_model_ds->setContentFromFile("$module_path/xml/content_models/islandora_genetic_edition_witness_ds_composite_model.xml", FALSE);
  $genetic_edition_witness_content_model->ingestDatastream($witness_model_ds);

  // Page content model.
  $genetic_edition_page_content_model = $connection->repository->constructObject('islandora:geneticEditionPageCModel');
  $genetic_edition_page_content_model->owner = 'fedoraAdmin';
  $genetic_edition_page_content_model->label = 'Islandora Genetic Edition Page Content Model';
  $genetic_edition_page_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL datastream.
  $page_model_ds = $genetic_edition_page_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $page_model_ds->label = 'DS-COMPOSITE-MODEL';
  $page_model_ds->mimetype = 'application/xml';
  $page_model_ds->setContentFromFile("$module_path/xml/content_models/islandora_genetic_edition_page_ds_composite_model.xml", FALSE);
  $genetic_edition_page_content_model->ingestDatastream($page_model_ds);

  // Genetic Edition collection.
  $genetic_edition_collection = $connection->repository->constructObject('islandora:genetic_edition_collection');
  $genetic_edition_collection->owner = 'fedoraAdmin';
  $genetic_edition_collection->label = 'Genetic Edition Collection';
  $genetic_edition_collection->models = 'islandora:collectionCModel';
  $genetic_edition_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection policy datastream.
  $ge_collection_policy_ds = $genetic_edition_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $ge_collection_policy_ds->label = 'Collection policy';
  $ge_collection_policy_ds->mimetype = 'application/xml';
  $ge_collection_policy_ds->setContentFromFile("$module_path/xml/collection/islandora_genetic_edition_collection_policy.xml", FALSE);
  $genetic_edition_collection->ingestDatastream($ge_collection_policy_ds);
  // TN datastream.
  $ge_collection_tn_ds = $genetic_edition_collection->constructDatastream('TN', 'M');
  $ge_collection_tn_ds->label = 'Thumbnail';
  $ge_collection_tn_ds->mimetype = 'image/png';
  $ge_collection_tn_ds->setContentFromFile("$module_path/images/folder.png", FALSE);
  $genetic_edition_collection->ingestDatastream($ge_collection_tn_ds);

  return array(
    'islandora_genetic_edition' => array(
      'title' => 'Islandora Genetic Edition',
      'objects' => array(
        $genetic_edition_content_model,
        $genetic_edition_witness_content_model,
        $genetic_edition_page_content_model,
        $genetic_edition_collection,
      ),
    ),
  );
}

/**
 * Implements hook_theme().
 */
/*
function islandora_genetic_edition_theme($existing, $type, $theme, $path) {
}
*/
